parameters:
  env(TMA_FILTER_ID): 1
  env(ELASTICSEARCH_URI): 'http://localhost:9200'
  env(ELASTICSEARCH_INDEX_TMA_ISSUES): ''
  tma_filter_id: '%env(TMA_FILTER_ID)%'
  elasticsearch.uri: '%env(ELASTICSEARCH_URI)%'
  elasticsearch.index.tma_issues: '%env(ELASTICSEARCH_INDEX_TMA_ISSUES)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Elasticsearch\ClientBuilder:
    factory: [ 'Elasticsearch\ClientBuilder', 'create' ]
    calls:
      - setHosts: [ ['%elasticsearch.uri%'] ]
      - setLogger: [ '@logger' ]

  Elasticsearch\Client:
    factory: [ '@Elasticsearch\ClientBuilder', 'build' ]

  App\TMA\Repository\TMAIssueRepository:
    arguments:
      $index: '%elasticsearch.index.tma_issues%'

  App\TMA\RecordTMAMetricsCommand:
    arguments:
      $tmaFilterId: '%tma_filter_id%'