parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Event,Exception,Helper,Model,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Repository\GitHub\PullRequestRepository:
        arguments:
            $repositoryOwner: '%env(GITHUB_REPOSITORY_OWNER)%'
            $repositoryName: '%env(GITHUB_REPOSITORY_NAME)%'

    public.logger:
        alias: 'logger'
        public: true

    Github\HttpClient\Builder:
    Lcobucci\JWT\Builder:

    Github\Client:
        factory:   ['@App\Factory\GitHubClientFactory', 'createGitHubClient']
        arguments:
            $gitHubAppId: '%env(GITHUB_APP_ID)%'
            $gitHubPrivateRsaKey: '%env(GITHUB_PRIVATE_RSA_KEY)%'
            $gitHubAppInstallationId: '%env(GITHUB_APP_INSTALLATION_ID)%'

    JoliCode\Slack\Api\Client:
        factory: ['JoliCode\Slack\ClientFactory', create]
        arguments: ['%env(SLACK_TOKEN)%']

    App\Dashboard\Query\ReviewEnvironments: '@App\Dashboard\Query\Adapter\FromGitHubHandlerReviewEnvironments'
    App\Dashboard\Query\PullRequestsToDeploy: '@App\Dashboard\Query\Adapter\FromGitHubHandlerPullRequestsToDeploy'
    App\Dashboard\Query\PullRequestsToMergeOnDev: '@App\Dashboard\Query\Adapter\FromGitHubHandlerPullRequestsToMergeOnDev'